sudo: false

language: node_js

node_js:
  - 10.3.0

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - app/node_modules

before_script:
  - meteor npm install

script:
  - npm test
